log:
  level: "info"
  # location to write the log file (default is not to have a log file)
  file: "./ecg.log"

anchore:
  url: http://localhost:8228
  user: admin
  password: $ECG_ANCHORE_PASSWORD
  http:
    insecure: true
    timeout-seconds: 10
